[package]
name = "tsp-pso"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mincost = {path = "../../../../mincost",features = ["pso","shuffle"]}
rand = "0.8"
