[package]
name = "mincost"
version = "0.1.0"
authors = ["Eric <xuzhenyutc@icloud.com>"]
edition = "2018"

[dependencies]
fastrand = "1.4"

[features]
ga = []
sa = []
pso = []

[workspace]
members = [
	"examples/ga_examples/bounded_decimal_encoding",
	"examples/ga_examples/binary_encoding",
]