[package]
name = "ga_example"
version = "0.1.0"
authors = ["Eric <zhenyuxu163@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
mincost = {path = "../../../mincost",features = ["ga"]}
